// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbjYnHGkgH3LiypFcQzsNu17dtV-w8rN0',
    appId: '1:331917739786:web:10671bff0cf9aab139dcf3',
    messagingSenderId: '331917739786',
    projectId: 'chat-application-7e969',
    authDomain: 'chat-application-7e969.firebaseapp.com',
    storageBucket: 'chat-application-7e969.firebasestorage.app',
    measurementId: 'G-4JQRFY8KGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoVFi6htaPz2tn0MQBaxakG1QWhlUlsI0',
    appId: '1:331917739786:android:e537bf69aeaa04e939dcf3',
    messagingSenderId: '331917739786',
    projectId: 'chat-application-7e969',
    storageBucket: 'chat-application-7e969.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUUsgx-IqBOWYhaB-7D7xvyaJ4Nz34fTQ',
    appId: '1:331917739786:ios:a8f6085aa46fb1a039dcf3',
    messagingSenderId: '331917739786',
    projectId: 'chat-application-7e969',
    storageBucket: 'chat-application-7e969.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );
}
